---
version: 2
builds:
  -  # First Build
    main: ./cmd/zoneomatic
    binary: bin/{{ .ProjectName }}
    ldflags: &ldflags >-
      -s -w
    targets: &targets
      - linux_amd64
      - linux_arm64
    env: &env
      - CGO_ENABLED=0

  - id: dnsfmt
    main: ./cmd/dnsfmt
    binary: bin/dnsfmt
    ldflags: *ldflags
    targets: *targets
    env: *env

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt"
  algorithm: sha512

archives:
  - id: tar
    formats: tar.gz
    files:
      - LICENSE
      - README.md
