---
version: 2
builds:
  -  # First Build
    env:
      - CGO_ENABLED=0
    main: ./cmd/zoneomatic
    ldflags: >-
      -s -w

    binary: bin/{{ .ProjectName }}
    targets:
      - linux_amd64
      - linux_arm64

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt"
  algorithm: sha512

archives:
  - id: tar
    formats: tar.gz
    files:
      - LICENSE
      - README.md
