---
version: 2
project_name: zoneomatic

builds:
  - id: zoneomatic
    main: ./cmd/zoneomatic
    binary: zoneomatic
    ldflags: &ldflags >-
      -s -w
      -X github.com/vooon/zoneomatic/internal/buildinfo.Version={{ .Version }}
      -X github.com/vooon/zoneomatic/internal/buildinfo.Commit={{ .Commit }}
      -X github.com/vooon/zoneomatic/internal/buildinfo.Branch={{ .Branch }}
      -X github.com/vooon/zoneomatic/internal/buildinfo.Date={{ .Date }}
    flags: &flags
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"
    env: &env
      - CGO_ENABLED=0
    targets: &targets
      - linux_amd64
      - linux_arm64

  - id: dnsfmt
    main: ./cmd/dnsfmt
    binary: dnsfmt
    ldflags: *ldflags
    flags: *flags
    mod_timestamp: "{{ .CommitTimestamp }}"
    targets: *targets
    env: *env

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt"
  algorithm: sha512

archives:
  - id: tar
    formats: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

dockers_v2:
  - id: zoneomatic-container
    dockerfile: Dockerfile
    ids:
      - zoneomatic
    images:
      - "{{ .Env.IMAGE_REPO }}"
    tags:
      - "{{ .Tag }}"
      - "{{ .Version }}"
      - "{{ .Major }}.{{ .Minor }}"
      - "latest"
      - "sha-{{ .ShortCommit }}"
    labels:
      org.opencontainers.image.description: "Zone-o-matic DNS API Server"
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.name: "zoneomatic"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.source: "{{ .GitURL }}"
      org.opencontainers.image.title: "zoneomatic"
      org.opencontainers.image.version: "{{ .Version }}"
    platforms:
      - linux/amd64
      - linux/arm64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
