---
version: 2
project_name: zoneomatic

builds:
  - id: zoneomatic
    main: ./cmd/zoneomatic
    binary: zoneomatic
    ldflags: &ldflags >-
      -s -w
      -X github.com/prometheus/common/version.Version={{ .Version }}
      -X github.com/prometheus/common/version.Revision={{ .Commit }}
      -X github.com/prometheus/common/version.Branch={{ .Branch }}
      -X github.com/prometheus/common/version.BuildDate={{ .Date }}
    flags: &flags
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"
    env: &env
      - CGO_ENABLED=0
    targets: &targets
      - linux_amd64
      - linux_arm64

  - id: dnsfmt
    main: ./cmd/dnsfmt
    binary: dnsfmt
    ldflags: *ldflags
    flags: *flags
    mod_timestamp: "{{ .CommitTimestamp }}"
    targets: *targets
    env: *env

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt"
  algorithm: sha512

archives:
  - id: tar
    formats: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
